{{- if not .Values.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
data:
  token: {{ .Values.crawler.token | b64enc }}
  {{- if .Values.crawler.cfg.s3.enabled }}
  awsAccessKeyId: {{ .Values.crawler.cfg.s3.accessKeyId | b64enc }}
  awsSecretAccessKey: {{ .Values.crawler.cfg.s3.secretAccessKey | b64enc }}
  {{- if .Values.crawler.cfg.s3.yandexcloud.privatekey }}
  privateKey: {{ .Values.crawler.cfg.s3.yandexcloud.privatekey | replace "\n" "\\n" | b64enc }}
  {{- end }}
  {{- end }}

  {{- if .Values.crawler.cfg.kafka.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.kafka.elements }}
  {{- if $val.password }}
  kafkaPasswords-{{ $key }}: {{ $val.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.crawler.cfg.database.postgres.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.database.postgres.elements }}
  databasePostgresConnStrings-{{ $key }}: {{ $val.connectionString | b64enc }}
  {{- end }}
  {{- end }}

  {{- if .Values.crawler.cfg.database.mysql.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.database.mysql.elements }}
  databaseMysqlConnStrings-{{ $key }}: {{ $val.connectionString | b64enc }}
  {{- end }}
  {{- end }}

  {{- if .Values.crawler.cfg.database.mssql.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.database.mssql.elements }}
  databaseMssqlConnStrings-{{ $key }}: {{ $val.connectionString | b64enc }}
  {{- end }}
  {{- end }}

type: Opaque
{{- end }}