apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-crawler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
data:
  SVRN_CRAWLER_LOG_LEVEL: "{{ .Values.crawler.cfg.log.level }}"
  SVRN_CRAWLER_DETECTIONTOOL_URL: "http://{{ .Release.Name }}-detection-tool:{{ .Values.detectionTool.service.port }}"
  {{- if .Values.prometheusAgent.enabled }}
  SVRN_CRAWLER_INSTRUMENTATION_METRICSENDER_ENABLED: "true"
  {{- end }}
  SVRN_CRAWLER_INSTRUMENTATION_LOGGER_ENABLED: "true"
  SVRN_CRAWLER_KAFKA_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_CRAWLER_KAFKA_CONSUMERLOGS_TOPIC: "{{ .Values.kafka.topics.logsTopicName }}"
  SVRN_CRAWLER_STATSCLIENT_CLIENT_ADDRESS: "stats.soveren.io:443"
  SVRN_CRAWLER_STATSCLIENT_CLIENT_TIMEOUT: "30s"
  SVRN_CRAWLER_STATSCLIENT_CLIENT_USETLS: "true"
  SVRN_CRAWLER_PRODUCER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_CRAWLER_PRODUCER_TOPICLOGS: "logs"
  SVRN_CRAWLER_CRAWL_DATABASE_CHECKINTERVAL: "{{ .Values.crawler.cfg.database.checkinterval }}"
  SVRN_CRAWLER_STATSCLIENT_GRPC_ADDRESS: "0.0.0.0:10350"
  SVRN_CRAWLER_STATSCLIENT_GRPC_USETLS: "{{ .Values.crawler.cfg.grpc.usetls }}"
  {{- if .Values.crawler.cfg.grpc.usetls }}
  SVRN_CRAWLER_STATSCLIENT_GRPC_CACERTIFICATE: "/etc/certs/ca.crt"
  SVRN_CRAWLER_STATSCLIENT_GRPC_CERTIFICATEH: "/etc/certs/tls.crt"
  SVRN_CRAWLER_STATSCLIENT_GRPC_KEYPATH: "/etc/certs/tls.key"
  {{- end }}