apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
data:
  token: {{ .Values.crawler.token | b64enc }}
  {{- if .Values.crawler.cfg.s3.enabled }}
  awsAccessKeyId: {{ .Values.crawler.cfg.s3.accessKeyId | b64enc }}
  awsSecretAccessKey: {{ .Values.crawler.cfg.s3.secretAccessKey | b64enc }}
  {{- end }}
  {{- if .Values.crawler.cfg.kafka.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.kafka.elements }}
  {{- if $val.password }}
  kafkaPasswords-{{ $key }}: {{ $val.password | b64enc }}
  Passwords-{{ $key }}: {{ $val.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.crawler.cfg.database.enabled }}
  {{- range $key, $val := .Values.crawler.cfg.database.elements }}
  {{- if $val.password }}
  databasePasswords-{{ $key }}: {{ $val.password | b64enc }}
  Passwords-{{ $key }}: {{ $val.password | b64enc }}
  {{- end }}
  {{- if $val.user }}
  databaseUsers-{{ $key }}: {{ $val.user | b64enc }}
  Users-{{ $key }}: {{ $val.user | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
type: Opaque