kafka:
  topics:
    eventsTopicName: events
    heartbeatTopicName: heartbeat
  embedded:
    enabled: true
    deploymentAnnotations: {}
    deploymentLabels: {}
    podAnnotations: {}
    podLabels: {}
    image:
      name: soveren/kafka
      tag: kraft
      pullPolicy: IfNotPresent
    env: []
    priorityClassName: ""
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        memory: "1024Mi"
    service:
      annotations: {}
      labels: {}
      port: 9092
    metrics:
      enabled: false
      port: 9308
  external:
    # kafka.external.brokers used only if kafka.embedded.enabled=false
    brokers: []

digger:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  token: ""
  image:
    name: soveren/digger
    tag: v0.13.2
    pullPolicy: Always
  env: []
  priorityClassName: ""
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"
  service:
    annotations: {}
    labels: {}
    port: 9000

detectionTool:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/detection-tool
    tag: v0.15.10
    pullPolicy: Always
  env: []
  priorityClassName: ""
  resources: 
    requests:
      memory: "3072Mi"
      cpu: "250m"
    limits:
      memory: "3584Mi"
      cpu: "2000m"
  service:
    annotations: {}
    labels: {}
    port: 8000

interceptor:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/interceptor
    tag: v0.13.2
    pullPolicy: Always
  env: []
  priorityClassName: ""
  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi
