kafka:
  topics:
    eventsTopicName: events
    heartbeatTopicName: heartbeat
  embedded:
    enabled: true
    deploymentAnnotations: {}
    deploymentLabels: {}
    podAnnotations: {}
    podLabels: {}
    image:
      name: soveren/kafka
      tag: 11_2.13-3.2.1
      pullPolicy: IfNotPresent
    env:
    - name: KAFKA_HEAP_OPTS
      value: -Xmx512m -Xms512m
    priorityClassName: ""
    resources:
      requests:
        cpu: "150m"
        memory: "1280Mi"
      limits:
        cpu: "200m"
        memory: "1280Mi"
    nodeSelector: {}
    affinity: {}
    tolerations: []
    service:
      annotations: {}
      labels: {}
      port: 9092
    metrics:
      enabled: true
      port: 9308
  external:
    # kafka.external.brokers used only if kafka.embedded.enabled=false
    brokers: []

digger:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  token: ""
  image:
    name: soveren/digger
    tag: v0.13.6
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      cpu: "1250m"
      memory: "512Mi"
    limits:
      cpu: "1500m"
      memory: "768Mi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    port: 9000

detectionTool:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/detection-tool
    tag: v0.17.11
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      memory: "3072Mi"
      cpu: "1000m"
    limits:
      memory: "3584Mi"
      cpu: "1100m"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    port: 8000

interceptor:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/interceptor
    tag: v0.13.6
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      cpu: "1250m"
      memory: "1536Mi"
    limits:
      cpu: "1500m"
      memory: "2048Mi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  metricsPort: 9090
  service:
    annotations: {}
    labels: {}
    port: 9090

prometheusAgent:
  enabled: true
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: prom/prometheus
    tag: v2.37.0
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources: 
    requests:
      memory: "192Mi"
      cpu: "75m"
    limits:
      memory: "192Mi"
      cpu: "75m"
  nodeSelector: {}
  affinity: {}
  tolerations: []
