kafka:
  topics:
    eventsTopicName: events
    heartbeatTopicName: heartbeat
    iplistTopicName: iplist
  embedded:
    enabled: true
    deploymentAnnotations: {}
    deploymentLabels: {}
    podAnnotations: {}
    podLabels: {}
    image:
      name: soveren/kafka
      tag: 11_2.13-3.2.3-1
      pullPolicy: IfNotPresent
    env:
    - name: KAFKA_HEAP_OPTS
      value: -Xmx512m -Xms512m
    priorityClassName: ""
    resources:
      requests:
        cpu: "100m"
        memory: "650Mi"
        ephemeral-storage: 5Gi
      limits:
        cpu: "200m"
        memory: "1024Mi"
        ephemeral-storage: 10Gi
    nodeSelector: {}
    affinity: {}
    tolerations: []
    service:
      annotations: {}
      labels: {}
      port: 9092
    metrics:
      enabled: true
      port: 9308
  external:
    # kafka.external.brokers used only if kafka.embedded.enabled=false
    brokers: []

digger:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  token: ""
  image:
    name: soveren/digger
    tag: v0.15.2
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1500m"
      memory: "768Mi"
      ephemeral-storage: 100Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    port: 9000
  cfg:
    log:
      level: error
    kubernetesfilterlist:
      # filter by kubernetes namespace definitions. Empty list allows everything. You can set it like this:
      # - namespace: default
      #   action: allow
      # - namespace: kube-system
      #   action: deny
      definitions:
        - namespace: "*"
          action: allow

detectionTool:
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/detection-tool
    tag: v1.2.2
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      cpu: "100m"
      memory: "1680Mi"
    limits:
      cpu: "1100m"
      memory: "2304Mi"
      ephemeral-storage: 200Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    port: 8000
  cfg:
    logging:
      level: error

interceptor:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: soveren/interceptor
    tag: v0.15.2
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "2048Mi"
      ephemeral-storage: 100Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  metricsPort: 9090
  service:
    annotations: {}
    labels: {}
    port: 9090
  cfg:
    log:
      level: error

prometheusAgent:
  enabled: true
  deploymentAnnotations: {}
  deploymentLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    name: prom/prometheus
    tag: v2.37.0
    pullPolicy: IfNotPresent
  env: []
  priorityClassName: ""
  resources: 
    requests:
      memory: "192Mi"
      cpu: "75m"
    limits:
      memory: "400Mi"
      cpu: "75m"
      ephemeral-storage: 100Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
