apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-detection-tool
  namespace: {{ .Release.Namespace }}
  {{- if .Values.detectionTool.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.detectionTool.deploymentAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "detectionTool.labels" . | nindent 4 }}
    {{- if .Values.detectionTool.deploymentLabels }}
    {{- toYaml .Values.detectionTool.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "detectionTool.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.detectionTool.podAnnotations }}
      annotations:
        {{- toYaml .Values.detectionTool.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "detectionTool.labels" . | nindent 8 }}
        {{- if .Values.detectionTool.podLabels }}
        {{- toYaml .Values.detectionTool.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.detectionTool.priorityClassName }}
      priorityClassName: "{{ .Values.detectionTool.priorityClassName }}"
      {{- end }}
      containers:
      - name: detection-tool
        image: {{ .Values.detectionTool.image.name }}:{{ .Values.detectionTool.image.tag }}
        imagePullPolicy: {{ .Values.detectionTool.image.pullPolicy }}
        ports:
        - containerPort: 8000
        resources:
          {{- toYaml .Values.detectionTool.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 8000
          timeoutSeconds: 3
      restartPolicy: Always
