apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-detection-tool
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "detectionTool.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "detectionTool.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "detectionTool.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: detection-tool
        image: {{ .Values.detectionTool.image.name }}:{{ .Values.detectionTool.image.tag }}
        imagePullPolicy: {{ .Values.detectionTool.image.pullPolicy }}
        ports:
        - containerPort: 8000
        resources:
          {{- toYaml .Values.detectionTool.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 8000
          timeoutSeconds: 3
      restartPolicy: Always
