apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-detection-tool
  namespace: {{ .Release.Namespace }}
  {{- if .Values.detectionTool.service.annotations }}
  annotations:
    {{- toYaml .Values.detectionTool.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "detectionTool.labels" . | nindent 4 }}
    {{- if .Values.detectionTool.service.labels }}
    {{- toYaml .Values.detectionTool.service.labels | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.detectionTool.service.port }}
    targetPort: 8000
  selector:
    {{- include "detectionTool.matchLabels" . | nindent 4 }}
