apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-detection-tool
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "detectionTool.labels" . | nindent 4 }}
data:
  SVRN_DETECTION_TOOL_LANG: {{ default "none" .Values.detectionTool.lang }}
  SVRN_DETECTION_TOOL_LOG_LEVEL: "{{ .Values.detectionTool.cfg.log.level }}"
  SVRN_DETECTION_TOOL_OTAREGISTRY_CLIENT_ADDRESS: "updates.soveren.io:443"
  SVRN_DETECTION_TOOL_UPDATE_CHECK_FREQ_SEC: "3600"
  {{- if eq .Values.detectionTool.kafkaEnabled "true" }}
  SVRN_DETECTION_TOOL_LOG_KAFKA: "{{ .Release.Name }}-kafka"
  {{- end }}

