apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digger
  namespace: {{ .Release.Namespace }}
  {{- if .Values.digger.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.digger.deploymentAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "digger.labels" . | nindent 4 }}
    {{- if .Values.digger.deploymentLabels }}
    {{- toYaml .Values.digger.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "digger.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.digger.podAnnotations }}
      annotations:
        {{- toYaml .Values.digger.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "digger.labels" . | nindent 8 }}
        {{- if .Values.digger.podLabels }}
        {{- toYaml .Values.digger.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.digger.priorityClassName }}
      priorityClassName: {{ .Values.digger.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-digger
      containers:
      - name: digger
        image: {{ .Values.digger.image.name }}:{{ .Values.digger.image.tag }}
        imagePullPolicy: {{ .Values.digger.image.pullPolicy }}
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-digger
        env:
        - name: SVRN_DIGGER_STATSCLIENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-token
              key: token
        {{- if .Values.digger.env }}
        {{- toYaml .Values.digger.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.digger.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 9000
          timeoutSeconds: 3
      restartPolicy: Always
