apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-digger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digger.labels" . | nindent 4 }}
data:
  SVRN_DIGGER_DETECTIONTOOL_URI: "http://{{ .Release.Name }}-detection-tool:{{ .Values.detectionTool.service.port }}"
  {{- if .Values.prometheusAgent.enabled }}
  SVRN_DIGGER_INSTRUMENTATION_METRICSENDER_ENABLED: "true"
  {{- end }}
  SVRN_DIGGER_KAFKA_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_TOPIC: "{{ .Values.kafka.topics.heartbeatTopicName }}"
  SVRN_DIGGER_KAFKA_CONSUMER_TOPIC: "{{ .Values.kafka.topics.eventsTopicName }}"
  SVRN_DIGGER_RESOLVER_KUBERNETES_ENABLED: "true"
  SVRN_DIGGER_STATSCLIENT_CLIENT_ADDRESS: "stats.soveren.io:443"
  SVRN_DIGGER_STATSCLIENT_CLIENT_TIMEOUT: "10s"
  SVRN_DIGGER_STATSCLIENT_CLIENT_USETLS: "true"
  SVRN_DIGGER_SAMPLER_ENABLED: "true"
  SVRN_DIGGER_SAMPLER_ACTIVECLUSTERING_ENABLED: "true"
  SVRN_DIGGER_IPLISTPRODUCER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_DIGGER_IPLISTPRODUCER_TOPIC: "{{ .Values.kafka.topics.iplistTopicName }}"
  SVRN_DIGGER_KUBERNETESFILTERLIST_DEFINITIONS: "{{ .Values.digger.kubernetesfilterlist.definitions }}"
