apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digger.labels" . | nindent 4 }}
data:
  token: {{ .Values.digger.token | b64enc }}
type: Opaque
