apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-digger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digger.labels" . | nindent 4 }}
data:
  SVRN_DIGGER_LOG_LEVEL: "{{ .Values.digger.cfg.log.level }}"
  SVRN_DIGGER_DETECTIONTOOL_URL: "http://{{ .Release.Name }}-detection-tool:{{ .Values.detectionTool.service.port }}"
  {{- if .Values.prometheusAgent.enabled }}
  SVRN_DIGGER_INSTRUMENTATION_METRICSENDER_ENABLED: "true"
  {{- end }}
  SVRN_DIGGER_INSTRUMENTATION_LOGGER_ENABLED: "true"
  SVRN_DIGGER_KAFKA_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_DIGGER_KAFKA_CONSUMERHEARTBEAT_TOPIC: "{{ .Values.kafka.topics.heartbeatTopicName }}"
  SVRN_DIGGER_KAFKA_CONSUMER_TOPIC: "{{ .Values.kafka.topics.eventsTopicName }}"
  SVRN_DIGGER_KAFKA_CONSUMERCONTROLRESPONSE_TOPIC: "{{ .Values.kafka.topics.controlResponseTopicName }}"
  SVRN_DIGGER_KAFKA_CONSUMERLOGS_TOPIC: "{{ .Values.kafka.topics.logsTopicName }}"
  SVRN_DIGGER_KAFKA_CONSUMERCONNECTIONMONITOR_TOPIC: "{{ .Values.kafka.topics.monitoredConnectionsTopicName }}"
  SVRN_DIGGER_RESOLVER_KUBERNETES_ENABLED: "true"
  SVRN_DIGGER_RESOLVER_EXCLUDELABELS: "{{ join "," .Values.digger.cfg.resolver.excludeLabels }}"
  SVRN_DIGGER_STATSCLIENT_CLIENT_ADDRESS: "{{ include "statsClientAddress" . }}"
  SVRN_DIGGER_STATSCLIENT_CLIENT_TIMEOUT: "10s"
  SVRN_DIGGER_STATSCLIENT_CLIENT_USETLS: "true"
  SVRN_DIGGER_STATSCLIENT_CLUSTERNAME: "{{ .Values.digger.clusterName }}"
  SVRN_DIGGER_SAMPLER_ENABLED: "true"
  SVRN_DIGGER_SAMPLER_ACTIVECLUSTERING_ENABLED: "{{ .Values.digger.cfg.sampler.activeClusteringEnabled }}"
  SVRN_DIGGER_SAMPLER_ACTIVECLUSTERINGUPDATER_ENABLED: "{{ .Values.digger.cfg.sampler.activeClusteringUpdaterEnabled }}"
  SVRN_DIGGER_IPLISTPRODUCER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_DIGGER_IPLISTPRODUCER_TOPIC: "{{ .Values.kafka.topics.iplistTopicName }}"
  SVRN_DIGGER_KUBERNETESFILTERLIST_DEFINITIONS: {{ toJson .Values.digger.cfg.kubernetesfilterlist.definitions | squote }}
  SVRN_DIGGER_PRODUCER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_DIGGER_PRODUCER_TOPICCONTROLREQUEST: "{{ .Values.kafka.topics.controlRequestTopicName }}"
  SVRN_DIGGER_PRODUCER_TOPICLOGS: "{{ .Values.kafka.topics.logsTopicName }}"
  SVRN_DIGGER_DETECTIONCORRECTOR_ENABLED: "{{ .Values.digger.cfg.detectioncorrector.enabled }}"
  SVRN_DIGGER_DETECTIONCORRECTOR_URL: "{{ .Values.digger.cfg.detectioncorrector.url }}"
  SVRN_DIGGER_DETECTIONCORRECTOR_TOKEN: "{{ .Values.digger.cfg.detectioncorrector.token }}"
  SVRN_DIGGER_DETECTIONCORRECTOR_TYPES: "{{ join "," .Values.digger.cfg.detectioncorrector.types }}"
  SVRN_DIGGER_GRPC_ADDRESS: "0.0.0.0:{{ .Values.digger.service.grpcPort }}"
