apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digger
  namespace: {{ .Release.Namespace }}
  {{- if .Values.digger.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.digger.deploymentAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "digger.labels" . | nindent 4 }}
    {{- if .Values.digger.deploymentLabels }}
    {{- toYaml .Values.digger.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "digger.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/digger-cm.yaml") . | sha256sum }}
      {{- if .Values.digger.podAnnotations }}
        {{- toYaml .Values.digger.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "digger.matchLabels" . | nindent 8 }}
        {{- if .Values.digger.podLabels }}
        {{- toYaml .Values.digger.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.digger.priorityClassName }}
      priorityClassName: {{ .Values.digger.priorityClassName }}
      {{- end }}
      {{- if .Values.digger.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.digger.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.digger.affinity }}
      affinity:
      {{- toYaml .Values.digger.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.digger.tolerations }}
      tolerations:
      {{- toYaml .Values.digger.tolerations | nindent 8 }}
      {{- end }}
      {{- with .Values.digger.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-digger
      containers:
      - name: digger
        image: {{ .Values.digger.image.name }}:{{ .Values.digger.image.tag }}
        imagePullPolicy: {{ .Values.digger.image.pullPolicy }}
        {{- if .Values.useExternalSecrets }}
        {{- if .Values.digger.image.command }}
        command:
        {{- range .Values.digger.image.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.digger.image.args }}
        args:
        {{- range .Values.digger.image.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        ports:
        - name: server
          containerPort: 9000
        - name: metricsender
          containerPort: 9100
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-digger
        env:
        {{- if not .Values.useExternalSecrets }}
        - name: SVRN_DIGGER_STATSCLIENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-token
              key: token
        {{- end }}
        - name: SVRN_DIGGER_INSTRUMENTATION_COMMANDS_DEFAULTNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.httpsProxy }}
        # HTTPS Proxy Settings
        - name: HTTPS_PROXY
          value: {{ .Values.httpsProxy }}
        {{- end }}
        {{- if .Values.httpsProxyNoProxy }}
        - name: NO_PROXY
          value: {{ tpl .Values.httpsProxyNoProxy . }}
        {{- end }}
        {{- if .Values.digger.env }}
        {{- toYaml .Values.digger.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.digger.resources | nindent 10 }}
        {{- if .Values.digger.securityContext }}
        securityContext:
          {{- toYaml .Values.digger.securityContext | nindent 10 }}
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: 9000
          timeoutSeconds: 3
      restartPolicy: Always
