---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
  {{- if .Values.interceptor.daemonSetAnnotations }}
  annotations:
    {{- toYaml .Values.interceptor.daemonSetAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}
    {{- if .Values.interceptor.daemonSetLabels }}
    {{- toYaml .Values.interceptor.daemonSetLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "interceptor.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/interceptor-cm.yaml") . | sha256sum }}
      {{- if .Values.interceptor.podAnnotations }}
        {{- toYaml .Values.interceptor.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "interceptor.matchLabels" . | nindent 8 }}
        {{- if .Values.interceptor.podLabels }}
        {{- toYaml .Values.interceptor.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.interceptor.priorityClassName }}
      priorityClassName: {{ .Values.interceptor.priorityClassName }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      containers:
      - name: interceptor
        image: {{ .Values.interceptor.image.name }}:{{ .Values.interceptor.image.tag }}
        imagePullPolicy: {{ .Values.interceptor.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: {{ .Values.interceptor.metricsPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-interceptor
        {{- if .Values.interceptor.env }}
        env:
        {{- toYaml .Values.interceptor.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.interceptor.resources | nindent 10 }}
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 30
