---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
  {{- if .Values.interceptor.daemonSetAnnotations }}
  annotations:
    {{- toYaml .Values.interceptor.daemonSetAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}
    {{- if .Values.interceptor.daemonSetLabels }}
    {{- toYaml .Values.interceptor.daemonSetLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "interceptor.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/interceptor-cm.yaml") . | sha256sum }}
      {{- if .Values.interceptor.podAnnotations }}
        {{- toYaml .Values.interceptor.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "interceptor.matchLabels" . | nindent 8 }}
        {{- if .Values.interceptor.podLabels }}
        {{- toYaml .Values.interceptor.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.interceptor.priorityClassName }}
      priorityClassName: {{ .Values.interceptor.priorityClassName }}
      {{- end }}
      {{- if .Values.interceptor.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.interceptor.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.interceptor.affinity }}
      affinity:
      {{- toYaml .Values.interceptor.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.interceptor.tolerations }}
      tolerations:
      {{- toYaml .Values.interceptor.tolerations | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      containers:
      - name: interceptor
        image: {{ .Values.interceptor.image.name }}:{{ .Values.interceptor.image.tag }}
        imagePullPolicy: {{ .Values.interceptor.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: {{ .Values.interceptor.metricsPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-interceptor
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if .Values.interceptor.env }}
        {{- toYaml .Values.interceptor.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.interceptor.resources | nindent 10 }}
        {{- if .Values.interceptor.securityContext }}
        securityContext:
          {{- toYaml .Values.interceptor.securityContext | nindent 10 }}
        {{- end }}
      - name: rpcapd
        image: {{ .Values.rpcapd.image.name }}:{{ .Values.rpcapd.image.tag }}
        imagePullPolicy: {{ .Values.rpcapd.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rpcapd.cfg.port }}
        env:
        - name: SVRN_RPCAPD_HOST
          value: "127.0.0.1"
        - name: SVRN_RPCAPD_PORT
          value: "{{ .Values.rpcapd.cfg.port }}"
        resources:
          {{- toYaml .Values.rpcapd.resources | nindent 10 }}
        {{- if .Values.rpcapd.securityContext }}
        securityContext:
          {{- toYaml .Values.rpcapd.securityContext | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: 30
