---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pods-reader
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-pods-reader
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-pods-reader
  apiGroup: rbac.authorization.k8s.io
