apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "interceptor.labels" . | nindent 4 }}
data:
  SVRN_INTERCEPTOR_LOG_LEVEL: "{{ .Values.interceptor.cfg.log.level }}"
  SVRN_INTERCEPTOR_PRODUCER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_INTERCEPTOR_PRODUCER_HEARTBEATTOPIC: "{{ .Values.kafka.topics.heartbeatTopicName }}"
  SVRN_INTERCEPTOR_PRODUCER_TOPIC: "{{ .Values.kafka.topics.eventsTopicName }}"
  SVRN_INTERCEPTOR_SOURCE_EXCLUDEDIFACE: "nflog,bluetooth-monitor,nfqueue,tunl0,ip6tnl0,lo,docker0,services1,eth0,cni0"
  SVRN_INTERCEPTOR_SOURCE_FILTER_URLFILTER: "/metrics,/healthz,/api/health,/api/v2/alive,/api/v2/detect"
  SVRN_INTERCEPTOR_STOPTIMEOUT: "55s"
  SVRN_INTERCEPTOR_INSTRUMENTATION_LISTENADDRESS: 0.0.0.0:{{ .Values.interceptor.metricsPort }}
  SVRN_INTERCEPTOR_INSTRUMENTATION_LOGGER_ENABLED: "true"
  SVRN_INTERCEPTOR_ASSEMBLER_STREAMMEMORYCONFIGURATION_TIMEOUT: "1s"
  SVRN_INTERCEPTOR_ASSEMBLER_STREAMMEMORYCONFIGURATION_MAXBUFFEREDPAGESTOTAL: "100000"
  SVRN_INTERCEPTOR_SOURCE_MAPPERTTL: "1m"
  SVRN_INTERCEPTOR_PRODUCER_BATCHSIZE: "1000"
  SVRN_INTERCEPTOR_PRODUCER_BATCHTIMEOUT: "100ms"
  SVRN_INTERCEPTOR_PRODUCER_CONTROLRESPONSETOPIC: "{{ .Values.kafka.topics.controlResponseTopicName }}"
  SVRN_INTERCEPTOR_PRODUCER_SENDERQUEUEWORKERPOOLCOUNT: "5"
  SVRN_INTERCEPTOR_RPCAPD_ENABLE: "true"
  SVRN_INTERCEPTOR_RPCAPD_HOST: "127.0.0.1"
  SVRN_INTERCEPTOR_RPCAPD_PORT: "{{ .Values.rpcapd.cfg.port }}"
  SVRN_INTERCEPTOR_CONNTRACKER_LINKERDPORT: "{{ .Values.interceptor.cfg.conntracker.linkerdPort }}"
  SVRN_INTERCEPTOR_CONNTRACKER_ENVOYPORT: "{{ .Values.interceptor.cfg.conntracker.envoyPort }}"
  SVRN_INTERCEPTOR_IPLISTCONSUMER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_INTERCEPTOR_IPLISTCONSUMER_TOPIC: "{{ .Values.kafka.topics.iplistTopicName }}"
  SVRN_INTERCEPTOR_MEMORY_LIMIT: "{{ .Values.interceptor.cfg.memory.limit | int }}"
  SVRN_INTERCEPTOR_MEMORY_SOFTMEMORYLIMITPERCENT: "{{ .Values.interceptor.cfg.memory.softLimitPercent | int }}"
  SVRN_INTERCEPTOR_CONTROLREQUESTCONSUMER_BROKERS: "{{ include "kafka.brokersStr" . }}"
  SVRN_INTERCEPTOR_CONTROLREQUESTCONSUMER_TOPIC: "{{ .Values.kafka.topics.controlRequestTopicName }}"
