{{- if .Values.kafka.embedded.persistentVolume.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-kafka-pvc
  namespace: {{ .Release.Namespace }}
{{- with .Values.kafka.embedded.persistentVolume.annotations  }}
  annotations:
    {{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    {{- if .Values.kafka.embedded.deploymentLabels }}
    {{- toYaml .Values.kafka.embedded.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
{{- with .Values.kafka.embedded.persistentVolume.accessModes }}
  accessModes:
    {{ toYaml . | indent 4 }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.kafka.embedded.persistentVolume.size | quote }}
{{- if .Values.kafka.embedded.persistentVolume.storageClass }}
  storageClassName: {{ .Values.kafka.embedded.persistentVolume.storageClass | quote }}
{{- end }}
{{- with .Values.kafka.embedded.persistentVolume.matchLabels }}
  selector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- end }}