{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
  egress: []
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-namespace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - podSelector: {}
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-digger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "digger.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: {{ .Values.networkPolicy.k8sApi.port }}
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-detection-tool
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "detectionTool.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
{{- end }}
