{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
  egress: []
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-namespace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - podSelector: {}
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-ranger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.metaLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ranger.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.networkPolicy.proxyIp }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.proxyIp }}
    {{- else }}
    - ports:
        - port: 10350
          protocol: TCP
    {{- end }}
    {{- if .Values.networkPolicy.rangerAdditionalEgress }}
    {{- range $rule := index .Values.networkPolicy.rangerAdditionalEgress }}
    - to:
        - ipBlock:
            cidr: {{ index $rule.host }}
      ports:
        - port: {{ index $rule.port }}
          protocol: {{ index $rule.protocol }}
    {{- end }}
    {{- end }}
{{- end }}
