name: Release Chart soveren-dar-sensor

on:
  push:
    tags:
    - 'soveren-dar-sensor-[0-9]+.[0-9]+.[0-9]+'
    - 'soveren-dar-sensor-[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

env:
  CHART_NAME: soveren-dar-sensor
  CR_OWNER: ${{ github.repository_owner }}
  CR_GIT_REPO: ${{ github.event.repository.name }}
  CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-releaser:v1.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Check that the git tag matches the chart version
      run: |
        apk -u add yq
        chart_version=$(yq .version charts/${CHART_NAME}/Chart.yaml)
        if [[ "${GITHUB_REF_NAME}" == "${CHART_NAME}-${chart_version}" ]]; then
          echo "Git tag: ${GITHUB_REF_NAME}"
          echo "Chart version: ${chart_version}"
          echo "OK: Git tag matches chart version"
        else
          echo "Git tag: ${GITHUB_REF_NAME}"
          echo "Chart version: ${chart_version}"
          echo "ERROR: Git tag and chart version are different"
          exit 1
        fi

    - name: Configure Git
      run: |
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    
    - name: Pack and release
      run: |
        cr package "charts/${CHART_NAME}"
        cr upload "charts/${CHART_NAME}"
        mkdir .cr-index
        cr index "charts/${CHART_NAME}" --push
